#!/usr/bin/env python3
"""
Regenerates businesslead/validate/data/postal_codes.py from GeoNames. Run it when you
want fresher codes:

    .venv/bin/python tools/build_geodata.py

It downloads every postal code GeoNames publishes (~20 MB), keeps the distinct
codes per country, and writes them into a Python module as one compressed blob
per country. Front-coding — each code stored as "how much of the previous code
it shares" plus the rest — takes the 1.1 million codes from 7 MB to under 1 MB,
which is what makes shipping them in a script reasonable at all.

GeoNames data is CC BY 4.0: https://creativecommons.org/licenses/by/4.0/
"""

from __future__ import annotations

import base64
import collections
import datetime
import io
import zipfile
import zlib
from pathlib import Path

import requests

SOURCE = "https://download.geonames.org/export/zip/allCountries.zip"
TARGET = (Path(__file__).resolve().parent.parent
          / "businesslead" / "validate" / "data" / "postal_codes.py")
SHARED_MAX = 61                      # keeps the marker inside printable ASCII


def front_code(codes: list[str]) -> bytes:
    """'560001','560002' → '560001','50002': store only what changed."""
    out, previous = [], ""
    for code in codes:
        shared = 0
        for old, new in zip(previous, code):
            if old != new:
                break
            shared += 1
        shared = min(shared, SHARED_MAX)
        out.append(chr(48 + shared) + code[shared:])
        previous = code
    return "\n".join(out).encode()


def main() -> int:
    print(f"↓ {SOURCE}")
    response = requests.get(SOURCE, timeout=300)
    response.raise_for_status()
    archive = zipfile.ZipFile(io.BytesIO(response.content))
    text = archive.read("allCountries.txt").decode("utf-8")

    by_country: dict[str, set[str]] = collections.defaultdict(set)
    for line in text.splitlines():
        country, code, *_ = line.split("\t")
        if code:
            by_country[country].add(code)

    total = sum(len(codes) for codes in by_country.values())
    print(f"  {total:,} codes across {len(by_country)} countries")

    blobs = {country: base64.b85encode(zlib.compress(front_code(sorted(codes)), 9)).decode()
             for country, codes in sorted(by_country.items())}
    counts = {country: len(codes) for country, codes in sorted(by_country.items())}

    lines = [
        '"""',
        "Every postal code GeoNames publishes, one compressed blob per country.",
        "",
        f"Generated by tools/build_geodata.py on {datetime.date.today()} — do not edit by hand.",
        f"{total:,} codes across {len(by_country)} countries.",
        "",
        f"Source: {SOURCE}",
        "Licence: CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/)",
        '"""',
        "",
        f'GENERATED = "{datetime.date.today()}"',
        f'SOURCE = "{SOURCE}"',
        f"TOTAL = {total}",
        f"SHARED_MAX = {SHARED_MAX}",
        "",
        "# country → how many distinct codes its blob holds",
        f"COUNTS = {counts!r}",
        "",
        "# country → zlib-compressed, front-coded, base85-armoured codes",
        "CODES = {",
    ]
    for country, blob in blobs.items():
        lines.append(f'    "{country}": (')
        for start in range(0, len(blob), 96):
            lines.append(f'        "{blob[start:start + 96]}"')
        lines.append("    ),")
    lines.append("}")
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"→ {TARGET.name}  {TARGET.stat().st_size / 1e6:.2f} MB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
